### ISSUE TITLE
wolframclient cannot locate kernel in Pop!_OS(linux distro)

### ISSUE THREAD

**Issue by evanhowington** [WolframResearch/WolframClientForPython#28]
![wolframClientBugScreenshot](https://user-images.githubusercontent.com/39414522/113328540-0ccda500-92e2-11eb-8284-acfa186127f2.png)

I can run the same code with Line 11 in windows10, but when I move to Pop!_OS(linux distro built on ubuntu) it is unable to locate the kernel.  I first attempted Line 11, which did not work and then I found in the docs I need to specify the kernel location, which I did but cannot find it for some reason.   

I verified this location using mathematica as well as going into the directory itself on the pc to verify it is present.  I also tried specifying "WolframKernel.sh" at the end of the file path but that did not help either.

**Comment by DbxDev** [comment]
For some unknown reasons `os.path.isfile` returns `false` for the kernel path.
You should be able to verify that using:
``` python
>>> from os.path import isfile
>>> isfile('/path/to/kernel')
```
(don't forget to set the path accordingly).

According the the [Python documentation](https://docs.python.org/3/library/os.path.html#os.path.exists) `isfile` calls `exists` which may return `False` on some platforms due to execute permissions.
